matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "3.5"
    - os: linux
      dist: trusty
      sudo: false
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      sudo: true
      language: python
      python: "3.7"
    - os: osx
      language: generic
      env: PYTHON_PKG_URL=https://www.python.org/ftp/python/3.6.4/python-3.6.4-macosx10.6.pkg
      sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O python.pkg "$PYTHON_PKG_URL"; sudo installer -pkg python.pkg -target /; rm python.pkg; fi
install:
  - python3 -m pip install --upgrade .[test] coverage codecov
script:
  - python3 -m coverage run -m unittest -b
after_success:
  - python3 -m codecov
# vim: ts=2:sts=2:sw=2:et
